[개념정리]

# Machine learning
- 애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습, 결과를 예측하는 알고리즘 기법 통칭
- 데이터를 기반으로 숨겨진 패턴을 인지해 해결
- 패턴을 학습, 기반한 예측을 수행
- predictive analysis (예측분석)

## 머신러닝의 분류
- 지도학습 (supervised learning) : 분류 & 회귀
- 비지도학습 (un-supervised learning)
- 강화학습 (reinforcement learning)

파이썬 & R ; 개발 생산성이 높고, 생태계가 활발

R ;  통계 분석 특화 언어

## 주요 패키지
- 머신러닝 패키지 ; 사이킷런
- 행렬 / 선형대수 / 통계 패키지 : 넘파이
- 데이터 핸들링 : 판다스
- 시각화 : 맷플롯립, 시본
- 그 외에 서드파티 라이브러리 등

데이터 처리 부분은 대부분 넘파이와 판다스

### 넘파이
- 자연과학, 공학에서 사용
- 빠른 배열 연산 속도를 보장

### 넘파이 ndarray 개요
- import numpy
- 다차원 배열을 쉽게 생성하고 다양한 연산 수행 가능
- Shape 변수 ; 크기 -> 행과 열의 수를 튜플 형대로 가지고 있음 -> 배열의 차원 알 수 있음
(명확한 1차원 데이터 혹은 다차원 데이터를 요구하는 경우  : 명확한 차원의 차수를 변환 방법을 알아야 오류 방지 가능)

#### ndarray 의 데이터 타입
- 숫자 : int형, unsigned형, float형, complex 타입
- 문자열
- 불

: 연산의 특성상 같은 데이터 타입만 가능 / 데이터 타입은 dtype 속성으로 확인 가능

: 리스트를 ndarray로 변경시 더 큰 데이터 타입으로 형변환을 일광적용

- astype() 메서드를 통해 알 수 있음 -> 인자로 원하는 타입을 문자열로 지정하면 됨
- 메모리로 데이터를 전체 로딩한 다음 이를 기반으로 알고리즘 적용 -> 대용량의 데이터 로딩시 수행속도가 느려지거나 메모리 부족으로 오류 발생 가능


### ndarray 편리하게 생성하기 -> arange, zeros, ones
- arange() : range()와 유사 기능 / default 함수 인자는 stop값, 1차원 ndarray를 만들어줌
- zeros() : 튜플 형태의 shape값을 입력 -> 모든 값을 0으로 채운 해당 shape의 ndarray를 생성
- ones()

### ndarray의 차원과 크기 변경 : resahpe()
- 지정 사이즈로 변경 불가시 오류발생 / 호환되는 새오룬 shape으로 변환
- ndarray는 stack or concat으로 결합시 각각의 ndarray의 형태를 통일해 유용하게 사용

### 넘파이의 ndarray의 데이터 세트 선택하기 :  indexing
- 특정 데이터만을 추출 : 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환
- 슬라이싱 : 연속된 인덱스 상의 ndarray를 추출하는 방식
- 팬시 인덱싱 : 해당 위치에 있는 데이터의 ndarray를 반환
- 불린 인덱싱 :  T/F 값 인덱싱 집합을 기반으로 T에 해당하는 인덱스 위치의 ndarray를 반환

##### 단일 값 추출
- 1차원과 2차원 ndarray에서의 데이터 접근의 차이는 2차원의 경우 ,로 분리된 로우와 칼럼 위치의 인덱스를 통해 접근하는 것
- axis 0 ; 로우 방향의 축을 의미 / axis 1은 칼럼 방향의 축 / 3차원의 경우 axis 2도 존재

##### 슬라이싱
- ':' 를 이용
- 1차원 ndarray에 슬라이싱을 적용 -> 유사하게 row, col 각각의 인덱스에 슬라이싱 적용

##### 불린 인덱싱
- 조건 필터링과 검색을 동시에 가능
- 단순히 []내에 원하는 필터링 조건만 넣으면 해당 조건을 만족하는 데이터 세트를 반환

##행렬의 정렬 - sort() & argsort
- 행렬 정렬 : np.sort()와 같이 넘파이에서 sort()를 호출하는 방식과 ndarray.sort()와 같은 행렬 자체에서 sort()를 호출하는 방식
- 행렬이 2차원 이상일 경우 : axis 축 값 설정을 통해 로우방향, 또는 칼럼 방향으로 정렬 수행
 - 정렬 행렬의 인덱스 반환 :  기존 원본 행렬의 원소에 대한 인덱스 필요시 np.argsort()를 이용
 - 넘파이의 ndarray는 메타 데이터를 가질 수 없음 - 실제 값과 그 값이 뜻하는 메타 데이터를 별도의 ndarray로 각각 가져야함

## 선형대수 연산 - 행렬 내적과 전치 행렬 구하기
- 행렬내적 (행렬곱) ; np.dot()
- 두 행렬 A, B의 내적은 왼쪽 행렬의 로우와 오른쪽 행렬의 칼럼의 원소들을 순차적으로 곱한뒤 그 결과를 모두 더한 값
- 전치 행렬 ; 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬 - A^t 로 표기 / transpose()를 이용



[필사]

In [2]:
import numpy as np

In [3]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array형태:', array1.shape)

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type:', type(array2))
print('array2 array형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array형태: (1, 3)


In [4]:
print('array1: {0}차원, array2 : {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2 : 2차원, array3: 2차원


In [37]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [38]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [7]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [39]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [9]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [10]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array3 = array1.reshape(5, 2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
array1.reshape(4, 3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [12]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [13]:
array1 = np.arange(10)
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [14]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('arrya5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
arrya5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [15]:
#1부터 9까지의 1차원 ndarray생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)
#index는 0부터 시작하므로 array1[2]는 3번째 index위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [16]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [17]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [18]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0, 0])
print('(row=0, col=1) index 가리키는 값:', array2d[0, 1])
print('(row=1, col=0) index 가리키는 값:', array2d[1, 0])
print('(row=2, col=2) index 가리키는 값:', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [19]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [20]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [21]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [22]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [23]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2]
print('array2d[[0,1],2] =>', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1],0:2] =>', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

array2d[[0,1],2] => [3, 6]
array2d[[0,1],0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


In [24]:
array1d = np.arange(start=1, stop=10)
#[] 안에 array1d > 5 boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값:', array3)

array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


In [25]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [26]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [27]:
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


In [28]:
org_array = np.array([ 3, 1, 9, 5])
print('원본 행렬:', org_array)
# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [29]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [30]:
array2d = np.array([[8, 12],
                    [7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [31]:
org_array = np.array([ 3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [32]:
org_array = np.array([ 3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [33]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [35]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [36]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
