# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
import numpy as np
print(np.__version__)
print(np.show_config())

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
zero_vector = np.zeros(10)
#길이가 10이고 모든 값이 0인 1차원 배열
print(zero_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
A = np.zeros((10,10))
print('nbytes:', A.nbytes)
print('itemsize:', A.itemsize)
print('nbytes:', A.size * A.itemsize)
#배열의 메모리 크기 확인
#배열 전체가 차지하는 바이트 수 = nbytes
#원소 1개가 차지하는 바이트 수 = itemize

nbytes: 800
itemsize: 8
nbytes: 800


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
zero_vector = np.zeros(10)
zero_vector[4] = 1
print(zero_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
A = np.arange(10, 50)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
A = np.arange(10)
A = A[::-1]
#슬라이싱은 역순으로 읽는 것
print(A)

[9 8 7 6 5 4 3 2 1 0]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
A = np.arange(9).reshape(3,3)
#나열하고 그걸 다시 모양 바꾸기
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
A = np.array([1,2,0,0,4,0])
print(np.nonzero(A)[0])

[0 1 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
A = np.eye((3))
#대각선이 1이고 나머지가 0인 단위 행렬
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
A = np.random.random((3,3,3))
print(A)

[[[0.00718472 0.18334518 0.49097282]
  [0.70643371 0.46226629 0.30197934]
  [0.97430252 0.05990848 0.36390552]]

 [[0.80801797 0.59846263 0.62120215]
  [0.58249868 0.84575659 0.53456305]
  [0.01052645 0.56575692 0.53462936]]

 [[0.16146535 0.71559845 0.36629748]
  [0.13875378 0.90383932 0.68644244]
  [0.83510183 0.38290155 0.25650754]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
A = np.random.random((10,10))
print(A.min(),A.max())
#최대 최소 값을 바로 구하는 것

0.0002001262187029118 0.9982786129344687


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
A = np.random.random(30)
print(A.mean())
#정리를 하고 그것의 평균

0.4872964672698156


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
A = np.ones((10,10), dtype = int)
A[1:-1,1:-1] = 0
print(A)
#테두리만 1로 만드는 것

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, True

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
#K=-1의 경우 주 대각선의 하나 아래를 의미
A = np.diag(1+np.arange(4),k=-1)
print(A)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
A = np.zeros((8,8), dtype = int)
A[1::2, ::2] = 1
A[::2, 1::2] = 1
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
A = np.arange(6*7*8).reshape((6,7,8))
print(np.unravel_index(99, A.shape))

(np.int64(1), np.int64(5), np.int64(3))


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
A = np.random.random((5,5))
A = (A - A.mean())/(A.max()-A.min())
print(A)

[[ 0.55659883  0.51455348  0.05952911 -0.14098546  0.03732669]
 [-0.22915987  0.16095128 -0.38211139  0.15040311  0.12069829]
 [-0.15203328  0.10144019 -0.21866498 -0.15579646  0.14842375]
 [-0.33036292  0.57628598 -0.2389791  -0.3924936   0.37491945]
 [ 0.10260203 -0.24769754  0.41768214 -0.42371402 -0.40941572]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [3]:
color = np.dtype([('r', np.ubyte), ('g', np.dtype), ('b', np.dtype), ('a', np.dtype)])
A = np.zeros(1, dtype=color)
print(A , A.dtype)

[(0, 0, 0, 0)] [('r', 'u1'), ('g', 'O'), ('b', 'O'), ('a', 'O')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
A = np.random.random((5,3))
B = np.random.random((3,2))
print(A@B)
# A = 5 x 3, B = 3 x 2일때 @를 통해서 5 x 2의 형태로 합쳐진다 -> 5행 2열로 나타나지는 것

[[1.44886174 0.76200197]
 [1.2497993  0.68932217]
 [0.74478646 0.34093331]
 [0.50931334 0.25815125]
 [0.48764675 0.21262769]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
A = np.arange(11)
A[(A>= 3)&(A<=8)] *= -1
# *=는 A*=B -> A = A*B를 의미
print(A)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
import numpy as np
Z = np.arange(3)
print('Z**Z', Z**Z)
print('2<<Z>>2', 2<<Z>>2)
print('Z<-Z',Z<-Z)
print('1j*Z',1j*Z)
print('Z/1/1',Z/1/1)
print('Z<Z>Z',Z<Z>Z)

Z**Z [1 1 4]
2<<Z>>2 [0 1 2]
Z<-Z [False False False]
1j*Z [0.+0.j 0.+1.j 0.+2.j]
Z/1/1 [0. 1. 2.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
import numpy as np
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_561/1110915717.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_561/1110915717.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_561/1110915717.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [4]:
A = np.array([0,10,10])
B = np.array([0, 10, 10])
print(np.intersect1d(A,B))

[ 0 10]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
import numpy as np
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/tmp/ipykernel_561/3053658764.py:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [ ]:
import numpy as np
print( np.arange('2016-07', '2016-08', dtype='datetime64[D]'))
#7월에 시작을 하고 8월부터는 하지 않는 것

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [1]:
import numpy as np
A = np.random.random(10)
B = np.random.random(10)
np.add(A,B)
np.negative(A,out=A)
np.divide(A,2,out=A)
np.multiply(A,B)
print(A,B)
#설명필요

[-0.01817481 -0.32816524 -0.08589044 -0.05701493 -0.46687393 -0.01406953
 -0.33956293 -0.27827373 -0.33135448 -0.05955485] [0.58601959 0.0662945  0.2000595  0.92373321 0.50922451 0.84559624
 0.08892022 0.02503029 0.52590226 0.89825031]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [2]:
import numpy as np
A = np.random.random(10)
print(A-A%1)
print(A//1)
#설명 필요

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
A = np.tile(np.arange(5), (5,1))
#np.arange(n)의 경우 0에서 n-1까지
#뒤의 (5,1)은 행 방향으로 5번, 열 방향으로 1번 반복하라는 것
print(A)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
A = np.random.random(10)
print('before:',A)
A.sort()
print('after:',A)

before: [0.55652535 0.69640607 0.52639474 0.55861773 0.21009819 0.58226417
 0.99964681 0.85855857 0.43940512 0.81884176]
after: [0.21009819 0.43940512 0.52639474 0.55652535 0.55861773 0.58226417
 0.69640607 0.81884176 0.85855857 0.99964681]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [ ]:
import numpy as np
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(np.array_equal(A,B))
#두 배열이 shape도 같고, 모든 원소도 정확히 같으면 True, 아니면 False

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [3]:
import numpy as np
Z = np.random.random((10,2))
print(Z)
#설명필요

[[0.0489775  0.2013344 ]
 [0.08243807 0.27856184]
 [0.51012273 0.41153605]
 [0.57400535 0.51764737]
 [0.2308888  0.35757531]
 [0.85052172 0.74339494]
 [0.00188345 0.87816957]
 [0.46403107 0.90486442]
 [0.97023233 0.89061451]
 [0.54168202 0.35251332]]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [ ]:
import numpy as np
Z = np.random.random(10)
Z[Z.argmax()] = 0
#배열Z에서 가장 큰 값 하나을 찾아서 0으로 바꾸는 것
print(Z)

[0.2757904  0.59694268 0.60845978 0.34229765 0.40727853 0.77592499
 0.07540651 0.684732   0.69255032 0.        ]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [4]:
import numpy as np
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v).argmin())
print(Z[index])

75


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [ ]:
import numpy as np
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
#다차원 배열 Z의 모든 원소를 하나씩 순회하면서 각원소의 좌표와 값을 동시에 가져오는 반복문
  print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [5]:
import numpy as np
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)

TypeError: 'str' object cannot be interpreted as an integer

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [7]:
# column 3
import numpy as np
Z = np.random.randint(0,10,(3,3))
print(Z)

[[6 5 1]
 [1 0 1]
 [4 6 8]]


29,30,34,38