#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [30]:
import numpy as np
A = np.random.random((5,3))
B = np.random.random((3,2))
print(A@B)
#넘파이를 이용해서 행렬의 곱을 계산하는 것

[[0.319077   1.24413651]
 [0.70031141 1.33585867]
 [0.31211712 0.97848954]
 [0.60478287 1.0616455 ]
 [0.33958689 0.70819735]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [4]:
A = np.arange(11)
A[(A>=3)*(A<=8)]*=-1
print(A)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [44]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [46]:
Z=np.arange(9).reshape(3,3)
#legal
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# Z<Z>Z -> X illegal

[[       1        1        4]
 [      27      256     3125]
 [   46656   823543 16777216]]
[[  0   1   2]
 [  4   8  16]
 [ 32  64 128]]
[[False False False]
 [False False False]
 [False False False]]
[[0.+0.j 0.+1.j 0.+2.j]
 [0.+3.j 0.+4.j 0.+5.j]
 [0.+6.j 0.+7.j 0.+8.j]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [20]:
import numpy as np
print(np.array(0) / np.array(0))
# '/'는 나누기를 실행하는 것 -> 0을 나누면 허수가 나오기에 nan이 나오는 것
print(np.array(0) // np.array(0))
# '//'는 몫을 나타내는 것이어서 가장 가까운 정수로 나타내는 것
print(np.array([np.nan]).astype(int).astype(float))
#int정수 값으로 변환 했다가 실수값으로 변환한 것

nan
0
[-9.22337204e+18]


/tmp/ipykernel_373/3967191932.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_373/3967191932.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_373/3967191932.py:6: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [26]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))
#공통 교집합을 찾는 것

[0 3 4 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False. nan!=1j


In [47]:
import numpy as np
print(np.sqrt(-1) == np.emath.sqrt(-1))
#제곱근의 경우에는 계산이 되는 것과 되지 않는 것을 같이 비교할 수 있어서
#두 값이 같지 않다고 나오는 것이다.
#왼쪽은 값이 없고 (nan이 뜬다), 오른쪽은 값이 존재하기에 같지 않다고 나오는 것이다

False


/tmp/ipykernel_373/1796280091.py:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [8]:
import numpy as np
print( np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [42]:
import numpy as np

A = np.ones(5)
B = np.ones(5)

np.add(A, B, out=B)        # B = A + B
np.divide(A, 2, out=A)     # A = A / 2
np.negative(A, out=A)      # A = -A
np.multiply(A, B, out=A)   # A = B * A

print(A)

[-1. -1. -1. -1. -1.]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [36]:
import numpy as np
Z = np.random.random(10) * 10
print('Z:', Z)
# method 1
print('floor:', np.floor(Z))
# method 2
print('astype(int):', Z.astype(int))

Z: [8.53282188 7.86499207 8.80982931 5.44029655 7.72455579 9.17605733
 9.3085527  6.90667315 5.82853356 1.79091756]
floor: [8. 7. 8. 5. 7. 9. 9. 6. 5. 1.]
astype(int): [8 7 8 5 7 9 9 6 5 1]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [48]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

A = np.tile(np.arange(5), (5,1))
print(A)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [49]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.00786957 0.1886728  0.36678574 0.52604176 0.58398655 0.67980268
 0.771296   0.81638984 0.8541326  0.96711722]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [50]:
import numpy as np
A = np.random.randint(0,2,(3,3))
B = np.random.randint(0,2,(3,3))
print(np.array_equal(A,B))

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [37]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]

R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)
#위의 두줄은 거리 밑의 두 줄은 각도를 의미하는 것이 된다.

[0.84677877 0.65053686 0.60803537 0.51853066 1.07729298 0.98009911
 0.78705755 0.73487248 0.69742584 0.89183725]
[0.20923519 0.2526666  1.07882952 0.07296722 0.62639261 1.12478937
 0.11997679 0.75753026 0.89254576 1.53131417]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [11]:
import numpy as np
Z = np.random.random(10)
Z[Z.argmax()] = 0
#배열Z에서 가장 큰 값 하나을 찾아서 0으로 바꾸는 것
print(Z)

[0.52627787 0.57761476 0.77745875 0.61763666 0.13274155 0.0349371
 0.0732752  0.         0.6037536  0.31338884]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [54]:
import numpy as np
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v).argmin())
print(Z[index])

31


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [55]:
import numpy as np
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [56]:
import numpy as np

n = 5
p = 8

Z = np.zeros((n, n))

np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 1.]
 [1. 1. 1. 0. 1.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [57]:
import numpy as np
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,0].argsort()])

[[4 4 1]
 [1 6 1]
 [2 8 6]]
[[1 6 1]
 [2 8 6]
 [4 4 1]]


In [58]:
print(Z)
print(Z[Z[:,1].argsort()])

[[4 4 1]
 [1 6 1]
 [2 8 6]]
[[4 4 1]
 [1 6 1]
 [2 8 6]]


In [59]:
print(Z)
print(Z[Z[:,2].argsort()])

[[4 4 1]
 [1 6 1]
 [2 8 6]]
[[4 4 1]
 [1 6 1]
 [2 8 6]]
